databases:
  - name: postgres
    ipAllowList: []
    databaseName: game_day_gambit_ror_fe
    user: game_day_gambit_ror_fe

services:
  - type: web
    name: game_day_gambit_ror_fe
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false